#Project Setup
general:
  unsafeMode: false
  automaticVersioning: true
  collectTelemetryData: false
  projectName: 'cloud-cap-s4ems-bp'
  extensionRepository: 'https://github.com/SAP/cloud-s4-sdk-pipeline.git'
  productiveBranch: 'master'

steps:
  artifactSetVersion:
    commitVersion: false
    timestampTemplate: '%Y%m%d%H%M%S'
  executeNpm:
    dockerImage: 'ppiper/node-browsers:v2'  
  cloudFoundryDeploy:
    dockerImage: 'ppiper/cf-cli'
    mtaDeployParameters: '-f --version-rule ALL'
  sapNexusStage:
    stagingProfile: 'integration'
    repositoryFormat: 'npm'
  sapNexusUploadArtifacts:
    packaging: 'mtar'
    buildDescriptorFile: 'mta.yaml'
    uploadFile: 'cloud-sf-extension-cap-sample_1.0.0.mtar'
    artifactType: 'mta'
  mtaBuild:
    mtaBuildTool: "cloudMbt"
stages:
  npmAudit:
    auditedAdvisories:
    # high
      - 550   
      - 593
      - 1184
      - 755
      - 1065 
      - 1164 
      - 1316 
      - 1324 
      - 1325 
    # moderate
      - 535
      - 1300 
      
#  backendIntegrationTests:
 #   createHdiContainer: true
  #  cloudFoundry:
   #   org: 'referenceappscf'
    #  space: 'SF_CAP'
     # apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      #credentialsId: 'cfdeployuser'

  lint:
    ui5BestPractices:
      failThreshold:
        error: 100
        warning: 500
        info: 1000
        
  #endToEndTests:
    #cfTargets:
     # - org: 'referenceappscf'
      #  space: 'SF_CAP'
       # apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
        #credentialsId: 'cfdeployuser'
    #appUrls:
     # - url: 'https://referenceappscf-sf-cap-media-server-srv.cfapps.eu10.hana.ondemand.com'
      #  credentialId: 'cfdeployuse. just tryingr'
        
  productionDeployment:
    cfTargets:
      - org: 'SA0176014160_AutomationSubAccountDomain'
        space: 'Dev'
        appName: 'cloud-sf-extension-cap-sample'
        apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
        credentialsId: 'C5287080' 
        
   #tmsUpload:
    #  - nodeName: 'devNode'
     #   credentialsId: 'tms-sk'
      #  customDescription: 'A custom description for the node upload'
       #namedUser: 'Piper-Pipeline'
        #mtaVersion: '*'
        #stashContent:
         # - 'buildResult' 
